### ISSUE TITLE
query and mutation implementation

### ISSUE THREAD

**Issue by anymaniax** [TanStack/angular-query#3]
Hello @maferland,

I don't know if this can help you but I tried to do an [implementation](https://github.com/anymaniax/angular-query/blob/feat-query/projects/angular-query/src/lib/angular-query.service.ts) for the useQuery and useMutation on my fork. I took my inspiration from the pull request in [svelte-query](https://github.com/TanStack/svelte-query).

**Comment by maferland** [comment]
Ohh, pretty neat! Looks like you're ahead of me. This is really helpfull.
I think we could merge #2 and your implementation together.

Would you like to open a PR so we can discuss how you did it? Good job 👏
I see you changed few things in the `/core` folder. Since this will be used in every binding lib we might have to work arround those changes.

@tannerlinsley told to me last night : 
> It's really just the utilities to bind angular components to those structures, eg. what the react-query/src/react directory is. Just bindings. So if you find yourself making replacements or enhancements to the queryCache/ concept, we'll probably need to address it.
